server:
  port: 9001

spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

rate:
  limit:
    hourly:
      limit: 5

infrastructure:
  services:
    weatherapi:
      endpoint: http://api.openweathermap.org
      path: /data/2.5/weather
      apiKey: 05ff608e03afa55e7655de03be8dbb21

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true